Universe 	       = vanilla
Initialdir  	   = /sphenix/user/hjheng/sPHENIXdNdEta/macros/
Executable 	       = $(Initialdir)/production_Nevt.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 48GB
Priority           = 20
job_lease_duration = 3600
nEvents            = 2000
InputfilelistIdx   = 0
FileName           = MVTXRecoClusters_NoPileup_Nevt2000_SingleJob_ana325private_singleEvtDst_20221019
skipEvt            = 0
Output  	       = $(Initialdir)/condor_Nevt/condor_out/out/condor_Nevt_processall_Nevt2000_SingleJob_20221019.out
Error              = $(Initialdir)/condor_Nevt/condor_out/err/condor_Nevt_processall_Nevt2000_SingleJob_20221019.err
Log  		       = $(Initialdir)/condor_Nevt/condor_out/log/condor_Nevt_processall_Nevt2000_SingleJob_20221019.log
Arguments          = "$(nEvents) $(InputfilelistIdx) $(FileName) $(skipEvt)"
Queue 1